server:
  port: 8080
  address: localhost
  tomcat:
    threads:
      max: 512
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: yeahnolja
  datasource:
    driver-class: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/yeah_nolja?serverTimezone=Asia/Seoul
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO #전체 로그 레벨 설정 (default = INFO)
    com:
      room:
        yeahnolja:
          domain:
            hotel:
              service: DEBUG #패키지와 그 하위 로그 레벨 설정