server:
  port: 8080
  address: localhost
  tomcat:
    threads:
      max: 512
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: yeahnolja
  datasource:
    driver-class: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/yeah_nolja?serverTimezone=Asia/Seoul
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true