insert into room (name, type, address, contact, star, description, rooms)
values ('조선팰리스','관광호텔업','서울특별시 종로구 새문안로 97 (당주동)','02-6388-5000',5,'포시즌스 호텔 서울 - <5성급:인증> - 포시즌스 호텔 서울은 5호선 광화문역 7번 출구에서 도보로 약 2분 거리에 있습니다. 호텔에서 도보로 약 5분이면 세종문화회관과 광화문 광장까지 가실 수 있습니다. 북촌 한옥마을과 명동 거리는 차로 약 10분 걸립니다.세 개의 레인을 갖춘 실내 수영장, 바이탈리티 풀, 어린이 풀, 스크린 골프, 피트니스센터 등 운동 시설이 구비되어 있습니다. 또한, 비즈니스센터, 스파, 사우나 시설도 마련되어 있습니다. 43개의 스위트/스폐셜 스위트 객실을 포함하여 총 317개의 객실이 있으며 객실에 따라 N서울 타워, 경복궁, 도시 등을 조망하실 수 있습니다. 올 데이 다이닝 뷔페 레스토랑, 정통 이탈리안 레스토랑, 아시안 레스토랑과 바를 포함한 총 7개의 식음 업장에서 다양한 맛을 경험하실 수 있습니다.',300);
# 경원재 앰배서더 인천,한국전통호텔업,인천광역시 연수구 테크노파크로 200 (송도동),032-729-1101,5,한옥 한국전통설명설명,350
# 시그니엘서울,관광호텔업,서울특별시 송파구 올림픽로 300 (신천동),02-3213-1000,5,"롯데월드타워 76층~101층에서 즐기는 파노라믹한 스카이라인. 미쉐린 스타 셰프 야닉 알레노의 다이닝과 세계 최고층에 위치한 웨딩&컨벤션. Live beyond expectations, SIGNIEL SEOUL",400

desc room;

select * from room;

select * from room where del_yn = 'N';

insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (1, 1, 1, 1, '2023-06-03 02:27:07', '2024-04-08 05:36:53', '2024-09-26 17:11:32', 'in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (2, 2, 2, 2, '2023-06-27 13:42:28', '2024-04-04 04:08:32', '2024-10-01 02:15:55', 'erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (3, 3, 3, 3, '2023-06-13 19:14:36', '2024-05-18 13:52:58', '2024-12-30 04:40:49', 'vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (4, 4, 4, 4, '2023-07-29 01:30:36', '2024-05-23 09:43:08', '2024-07-12 05:01:38', 'non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (5, 5, 5, 5, '2023-07-05 06:02:06', '2024-05-01 12:43:19', '2024-10-25 05:30:14', 'purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (6, 6, 6, 6, '2023-08-04 13:54:44', '2024-04-03 16:26:49', '2024-10-09 17:28:43', 'enim leo rhoncus sed vestibulum sit amet cursus id turpis');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (7, 7, 7, 7, '2023-07-17 17:06:41', '2024-06-03 21:35:56', '2024-12-02 02:36:01', 'vel sem sed sagittis nam congue risus semper porta volutpat');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (8, 8, 8, 8, '2023-07-07 13:41:36', '2024-04-26 11:34:46', '2024-09-30 14:07:09', 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (9, 9, 9, 9, '2023-08-24 14:31:12', '2024-05-05 08:31:59', '2024-09-19 06:10:51', 'aenean auctor gravida sem praesent id massa id nisl venenatis');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (10, 10, 10, 10, '2023-07-05 19:08:49', '2024-04-14 04:29:20', '2024-07-06 17:21:10', 'platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (11, 11, 11, 11, '2023-06-27 19:48:24', '2024-04-24 15:03:25', '2024-07-29 23:13:13', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (12, 12, 12, 12, '2023-09-11 13:26:11', '2024-05-23 15:44:26', '2024-08-18 05:25:36', 'volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (13, 13, 13, 13, '2023-07-01 14:49:27', '2024-05-05 12:24:03', '2024-12-16 20:02:40', 'quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (14, 14, 14, 14, '2023-08-04 05:46:43', '2024-04-18 17:57:40', '2024-09-20 07:05:48', 'odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (15, 15, 15, 15, '2023-07-13 12:36:30', '2024-06-28 14:05:04', '2024-12-06 15:27:46', 'lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (16, 16, 16, 16, '2023-06-03 19:46:32', '2024-06-08 08:57:02', '2024-09-20 06:18:46', 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (17, 17, 17, 17, '2023-07-27 09:55:15', '2024-06-24 10:15:49', '2024-07-31 01:54:25', 'eu felis fusce posuere felis sed lacus morbi sem mauris laoreet');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (18, 18, 18, 18, '2023-08-18 15:22:37', '2024-06-10 20:02:01', '2024-11-20 23:22:14', 'in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (19, 19, 19, 19, '2023-07-18 23:36:12', '2024-04-21 06:04:38', '2024-10-17 10:05:30', 'morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (20, 20, 20, 20, '2023-06-08 02:49:02', '2024-06-09 15:58:50', '2024-08-01 03:33:19', 'a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (21, 21, 21, 21, '2023-08-22 11:39:53', '2024-04-29 14:30:04', '2024-11-27 05:20:07', 'sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (22, 22, 22, 22, '2023-06-13 23:33:32', '2024-04-15 13:25:50', '2024-08-12 05:50:17', 'praesent blandit nam nulla integer pede justo lacinia eget tincidunt');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (23, 23, 23, 23, '2023-06-15 21:56:47', '2024-05-01 02:29:00', '2024-09-18 03:12:15', 'sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (24, 24, 24, 24, '2023-09-11 03:52:21', '2024-04-30 16:08:45', '2024-12-25 23:36:24', 'nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (25, 25, 25, 25, '2023-06-22 04:56:08', '2024-05-01 15:48:51', '2024-10-31 00:00:37', 'orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (26, 26, 26, 26, '2023-06-04 15:22:34', '2024-04-02 01:41:13', '2024-09-04 21:02:45', 'blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (27, 27, 27, 27, '2023-06-24 23:09:02', '2024-05-07 12:36:01', '2024-08-14 19:08:43', 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (28, 28, 28, 28, '2023-09-17 20:08:49', '2024-04-16 02:27:13', '2024-07-02 21:17:00', 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (29, 29, 29, 29, '2023-09-13 14:58:42', '2024-05-02 21:19:59', '2024-09-16 15:00:46', 'nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (30, 30, 30, 30, '2023-08-06 06:43:17', '2024-04-15 01:42:17', '2024-12-25 09:03:30', 'malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (31, 31, 31, 31, '2023-07-22 05:55:31', '2024-06-07 15:02:26', '2024-07-05 11:55:09', 'curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (32, 32, 32, 32, '2023-08-16 23:13:17', '2024-06-01 20:20:27', '2024-10-02 02:03:14', 'ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (33, 33, 33, 33, '2023-08-24 08:48:10', '2024-04-16 11:49:17', '2024-08-27 13:23:40', 'erat curabitur gravida nisi at nibh in hac habitasse platea');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (34, 34, 34, 34, '2023-09-15 18:42:52', '2024-06-23 06:44:10', '2024-12-22 09:27:35', 'maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (35, 35, 35, 35, '2023-08-13 21:29:38', '2024-04-04 23:08:18', '2024-09-04 12:59:43', 'augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (36, 36, 36, 36, '2023-07-20 19:10:14', '2024-05-16 22:27:24', '2024-11-16 01:06:02', 'vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (37, 37, 37, 37, '2023-08-08 23:47:49', '2024-05-30 09:49:52', '2024-09-21 20:25:40', 'habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (38, 38, 38, 38, '2023-07-30 02:52:29', '2024-06-09 07:59:12', '2024-11-04 14:19:26', 'dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (39, 39, 39, 39, '2023-09-13 07:21:14', '2024-04-01 18:32:40', '2024-09-15 11:12:38', 'orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (40, 40, 40, 40, '2023-06-18 18:49:59', '2024-04-24 08:22:48', '2024-12-10 01:56:27', 'varius integer ac leo pellentesque ultrices mattis odio donec vitae');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (41, 41, 41, 41, '2023-07-21 05:46:17', '2024-04-16 18:59:06', '2024-10-05 04:26:40', 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (42, 42, 42, 42, '2023-07-01 03:11:40', '2024-04-30 18:37:10', '2024-10-28 09:26:35', 'nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (43, 43, 43, 43, '2023-09-02 17:10:36', '2024-04-07 12:48:30', '2024-10-29 01:09:56', 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (44, 44, 44, 44, '2023-09-20 03:18:04', '2024-05-21 07:36:27', '2024-11-14 07:03:14', 'venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (45, 45, 45, 45, '2023-07-30 19:16:50', '2024-05-25 18:21:10', '2024-09-12 08:31:48', 'eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt');
insert into reservation (id, room_id, people, price, reservation_date, check_in, check_out, notice) values (46, 46, 46, 46, '2023-07-13 01:34:25', '2024-06-12 13:42:38', '2024-09-01 05:46:53', 'curabitur in libero ut massa volutpat convallis morbi odio odio elementum');


insert into room (id, room_id, name, type, people, price, information) values (1, 1, 'Sydel Fores', 'Twinte', 1, 1, 'odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed');
insert into room (id, room_id, name, type, people, price, information) values (2, 2, 'Nichole Laing', 'Oodoo', 2, 2, 'imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo');
insert into room (id, room_id, name, type, people, price, information) values (3, 3, 'Eloisa Mansford', 'Yodoo', 3, 3, 'fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum');
insert into room (id, room_id, name, type, people, price, information) values (4, 4, 'Malia Cunradi', 'Kwideo', 4, 4, 'non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla');
insert into room (id, room_id, name, type, people, price, information) values (5, 5, 'Jeanine Alexandrescu', 'Gigabox', 5, 5, 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla');
insert into room (id, room_id, name, type, people, price, information) values (6, 7, 'Chaddie Boole', 'Midel', 6, 6, 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede');
insert into room (id, room_id, name, type, people, price, information) values (7, 8, 'Tynan Ebbetts', 'Voolia', 7, 7, 'vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget');
insert into room (id, room_id, name, type, people, price, information) values (8, 9, 'Markos Trillow', 'Tavu', 8, 8, 'at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis');
insert into room (id, room_id, name, type, people, price, information) values (9, 12, 'Katya Brombell', 'Oyondu', 9, 9, 'odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt');
insert into room (id, room_id, name, type, people, price, information) values (10, 13, 'Elspeth Niese', 'Ailane', 10, 10, 'luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique');
insert into room (id, room_id, name, type, people, price, information) values (11, 14, 'Dylan Duke', 'Zoomcast', 11, 11, 'turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh');
insert into room (id, room_id, name, type, people, price, information) values (12, 15, 'Georgie Lorincz', 'Twiyo', 12, 12, 'morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit');
insert into room (id, room_id, name, type, people, price, information) values (13, 17, 'Martin Jahndel', 'Aimbu', 13, 13, 'tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id');
insert into room (id, room_id, name, type, people, price, information) values (14, 18, 'Melly Anetts', 'Dazzlesphere', 14, 14, 'praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo');
insert into room (id, room_id, name, type, people, price, information) values (15, 21, 'Phillip Kelcher', 'Devcast', 15, 15, 'eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui');
insert into room (id, room_id, name, type, people, price, information) values (16, 22, 'Reg Camsey', 'InnoZ', 16, 16, 'eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis');
insert into room (id, room_id, name, type, people, price, information) values (17, 23, 'Ysabel Cornell', 'Jetpulse', 17, 17, 'vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper');
insert into room (id, room_id, name, type, people, price, information) values (18, 24, 'Care Fernao', 'Wordpedia', 18, 18, 'lacinia eget tincidunt eget tempus');
insert into room (id, room_id, name, type, people, price, information) values (19, 26, 'Gilli McShane', 'Photojam', 19, 19, 'in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis');
insert into room (id, room_id, name, type, people, price, information) values (20, 27, 'Dorree Patis', 'Babblestorm', 20, 20, 'amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into room (id, room_id, name, type, people, price, information) values (21, 29, 'Shannon Skea', 'Vinder', 21, 21, 'enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque');
insert into room (id, room_id, name, type, people, price, information) values (22, 30, 'Karlie Melton', 'Browseblab', 22, 22, 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing');
insert into room (id, room_id, name, type, people, price, information) values (23, 32, 'Josie Chiles', 'Nlounge', 23, 23, 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa');
insert into room (id, room_id, name, type, people, price, information) values (24, 33, 'Angel Behan', 'Jaxbean', 24, 24, 'interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum');
insert into room (id, room_id, name, type, people, price, information) values (25, 34, 'Felix Allix', 'Jayo', 25, 25, 'curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam');
insert into room (id, room_id, name, type, people, price, information) values (26, 35, 'Sande Sprowles', 'Jabberstorm', 26, 26, 'primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit');
insert into room (id, room_id, name, type, people, price, information) values (27, 36, 'Merrill Swadlen', 'Dabjam', 27, 27, 'justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium');
insert into room (id, room_id, name, type, people, price, information) values (28, 37, 'Kittie Lorenzin', 'Devpulse', 28, 28, 'orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed');
insert into room (id, room_id, name, type, people, price, information) values (29, 58, 'Robena Handrock', 'Tekfly', 29, 29, 'ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque');
insert into room (id, room_id, name, type, people, price, information) values (30, 59, 'Laina McBride', 'Photospace', 30, 30, 'lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem');
insert into room (id, room_id, name, type, people, price, information) values (31, 60, 'Roderic Haighton', 'Blognation', 31, 31, 'libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac');
insert into room (id, room_id, name, type, people, price, information) values (32, 61, 'Benetta Yeatman', 'Photojam', 32, 32, 'ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu');
insert into room (id, room_id, name, type, people, price, information) values (33, 62, 'Trista Twitchett', 'Jaxspan', 33, 33, 'interdum mauris ullamcorper purus sit amet nulla');
insert into room (id, room_id, name, type, people, price, information) values (34, 63, 'Thorndike Dahlman', 'Twitterlist', 34, 34, 'eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut');
insert into room (id, room_id, name, type, people, price, information) values (35, 64, 'Isidro MacFarlane', 'Viva', 35, 35, 'est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius');
insert into room (id, room_id, name, type, people, price, information) values (36, 76, 'Blithe Makey', 'Twitterlist', 36, 36, 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum');
insert into room (id, room_id, name, type, people, price, information) values (37, 84, 'Kristien Warry', 'Skippad', 37, 37, 'et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum');
insert into room (id, room_id, name, type, people, price, information) values (38, 87, 'Alex Hendrikse', 'Eazzy', 38, 38, 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et');
insert into room (id, room_id, name, type, people, price, information) values (39, 88, 'Fanny Fewtrell', 'LiveZ', 39, 39, 'quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id');
insert into room (id, room_id, name, type, people, price, information) values (40, 112, 'Grove Lusty', 'Brainlounge', 40, 40, 'eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget');
insert into room (id, room_id, name, type, people, price, information) values (41, 116, 'Skelly Gracewood', 'Jatri', 41, 41, 'tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut');
insert into room (id, room_id, name, type, people, price, information) values (42, 121, 'Helge Gummow', 'Brainbox', 42, 42, 'amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl');
insert into room (id, room_id, name, type, people, price, information) values (43, 122, 'Bail Wyllie', 'Vinte', 43, 43, 'lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut');
insert into room (id, room_id, name, type, people, price, information) values (44, 124, 'Melinde Levins', 'Trilia', 44, 44, 'proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue');
insert into room (id, room_id, name, type, people, price, information) values (45, 133, 'Lev Masters', 'Bluezoom', 45, 45, 'eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac');
insert into room (id, room_id, name, type, people, price, information) values (46, 134, 'Pooh Fayerbrother', 'Mita', 46, 46, 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus');

